#!/usr/bin/env bash
set -eux -o pipefail
dr=${DOCKER_REGISTRY:-fiji.lbl.gov/bdgp}
img=${DOCKER_IMAGE:-$(basename "$(cd "$(dirname "$0")" && pwd)")}
token=$(kubectl get secrets/gitlab-docker-k8s --template={{.data.token}} |base64 -d || true)
project_id=$(kubectl get secrets/gitlab-docker-k8s --template={{.data.simsplice}} |base64 -d || true)
if [[ -z ${project_id} ]]; then
  read -s -p 'Enter simsplice gitlab project ID number: ' project_id; echo
  kubectl patch secret gitlab-docker-k8s --type=json -p '[{"op": "add", "path": "/data/simsplice", "value": "'"$(echo "$project_id" |base64)"'"}]'
fi
docker pull "$dr/$img"
DOCKER_BUILDKIT=1 docker build --build-arg token="$token" --build-arg project_id="$project_id" --progress plain --ssh default="$SSH_AUTH_SOCK" -t "$dr/$img" "$@" -- "$(dirname "$0")"
docker push "$dr/$img"
k8script.py --launcher -i "$dr/$img" sh -c 'echo /usr/bin/simsplice; echo /usr/bin/genvcf; echo /usr/bin/liftover'
